version: '3'

services:
  frontend-dev:
    image: frontend-dev
    container_name: frontend-dev
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000

networks:
  myytnetwork:
    driver: bridge
