version: '3'

services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
    networks: 
      - myytnetwork
    depends_on:
      - frontend
  frontend:
    stdin_open: true
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    tty: true
    networks: 
      - myytnetwork
    ports:
      - 3000:3000

networks:
  myytnetwork:
    driver: bridge
